/**
 * Generates `dist/tokens.css` and `dist/theme-cssvars.json` from the TypeScript
 * token modules.
 *
 * Two consumers, one source:
 *  - the docs site imports `dist/tokens.css` directly;
 *  - the registry theme item (`pixeldosa-theme`) embeds `dist/theme-cssvars.json`
 *    so a consumer running `shadcn add` gets the same values written into their
 *    own stylesheet.
 *
 * Running this as a build step rather than maintaining a parallel CSS file is the
 * only way "tokens are the single source of truth" survives contact with a second
 * distribution channel.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  colorsDark,
  colorsLight,
  fontSize,
  radius,
  type ColorScale,
} from "../src/design-tokens.js";
import { duration, easing, stagger } from "../src/motion-tokens.js";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, "../dist");

const seconds = (s: number) => `${Math.round(s * 1000)}ms`;
const bezier = (b: readonly number[]) => `cubic-bezier(${b.join(", ")})`;

/** Motion tokens exposed to CSS so non-Motion components can still honour them. */
const motionVars: Record<string, string> = {
  "--pd-duration-instant": seconds(duration.instant),
  "--pd-duration-fast": seconds(duration.fast),
  "--pd-duration-base": seconds(duration.base),
  "--pd-duration-slow": seconds(duration.slow),
  "--pd-duration-deliberate": seconds(duration.deliberate),
  "--pd-ease-standard": bezier(easing.standard),
  "--pd-ease-decelerate": bezier(easing.decelerate),
  "--pd-ease-accelerate": bezier(easing.accelerate),
  "--pd-stagger-tight": seconds(stagger.tight),
  "--pd-stagger-base": seconds(stagger.base),
  "--pd-stagger-loose": seconds(stagger.loose),
};

const themeVars: Record<string, string> = {
  radius: radius.base,
  ...motionVars,
};

const toVars = (scale: ColorScale) =>
  Object.entries(scale)
    .map(([key, value]) => `  --${key}: ${value};`)
    .join("\n");

const toBlock = (vars: Record<string, string>) =>
  Object.entries(vars)
    .map(([key, value]) => `  ${key.startsWith("--") ? key : `--${key}`}: ${value};`)
    .join("\n");

const themeInline = [
  ...Object.keys(colorsLight).map((key) => `  --color-${key}: var(--${key});`),
  "  --radius-sm: calc(var(--radius) - 4px);",
  "  --radius-md: calc(var(--radius) - 2px);",
  "  --radius-lg: var(--radius);",
  "  --radius-xl: calc(var(--radius) + 4px);",
  ...Object.entries(fontSize).map(
    ([key, [size, leading]]) => `  --text-${key}: ${size};\n  --text-${key}--line-height: ${leading};`
  ),
].join("\n");

const css = `/* GENERATED by @pixeldosa/tokens — do not edit. Run \`pnpm --filter @pixeldosa/tokens build\`. */

:root {
${toBlock(themeVars)}
${toVars(colorsLight)}
}

.dark {
${toVars(colorsDark)}
}

@theme inline {
${themeInline}
}
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, "tokens.css"), css, "utf8");
writeFileSync(
  resolve(outDir, "theme-cssvars.json"),
  `${JSON.stringify(
    {
      theme: themeVars,
      light: Object.fromEntries(Object.entries(colorsLight)),
      dark: Object.fromEntries(Object.entries(colorsDark)),
    },
    null,
    2
  )}\n`,
  "utf8"
);

console.log(`@pixeldosa/tokens → ${outDir}/tokens.css`);
console.log(`@pixeldosa/tokens → ${outDir}/theme-cssvars.json`);
